# Financial and Economic Data Applications

The use of Python in the financial industry has been increasing rapidly since 2005, led
largely by the maturation of libraries (like NumPy and pandas) and the availability of
skilled Python programmers. Institutions have found that Python is well-suited both
as an interactive analysis environment as well as enabling robust systems to be devel-
oped often in a fraction of the time it would have taken in Java or C++. Python is also
an ideal glue layer; it is easy to build Python interfaces to legacy libraries built in C or
C++.

While the field of financial analysis is broad enough to fill an entire book, I hope to
show you how the tools in this book can be applied to a number of specific problems
in finance. As with other research and analysis domains, too much programming effort
is often spent wrangling data rather than solving the core modeling and research prob-
lems. I personally got started building pandas in 2008 while grappling with inadequate
data tools.

In these examples, Iâ€™ll use the term cross-section to refer to data at a fixed point in time.
For example, the closing prices of all the stocks in the S&P 500 index on a particular
date form a cross-section. Cross-sectional data at multiple points in time over multiple
data items (for example, prices together with volume) form a panel. Panel data can
either be represented as a hierarchically-indexed DataFrame or using the three-dimen-
sional Panel pandas object.

# Data Munging Topics

## Time Series and Cross-Section Alignment

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stock_px.csv")
df

,Unnamed: 0,AA,AAPL,GE,IBM,JNJ,MSFT,PEP,SPX,XOM
0,1990-02-01 00:00:00,4.98,7.86,2.87,16.79,4.27,0.51,6.04,328.79,6.12
1,1990-02-02 00:00:00,5.04,8.00,2.87,16.89,4.37,0.51,6.09,330.92,6.24
2,1990-02-05 00:00:00,5.07,8.18,2.87,17.32,4.34,0.51,6.05,331.85,6.25
3,1990-02-06 00:00:00,5.01,8.12,2.88,17.56,4.32,0.51,6.15,329.66,6.23
4,1990-02-07 00:00:00,5.04,7.77,2.91,17.93,4.38,0.51,6.17,333.75,6.33
5,1990-02-08 00:00:00,5.04,7.71,2.92,17.86,4.46,0.51,6.22,332.96,6.35
6,1990-02-09 00:00:00,5.06,8.00,2.94,17.82,4.49,0.52,6.24,333.62,6.37
7,1990-02-12 00:00:00,4.96,7.94,2.89,17.58,4.46,0.52,6.23,330.08,6.22
8,1990-02-13 00:00:00,4.91,8.06,2.88,17.95,4.43,0.52,6.09,331.02,6.23
9,1990-02-14 00:00:00,4.94,8.00,2.89,18.04,4.47,0.52,6.10,332.01,6.20
10,1990-02-15 00:00:00,4.99,8.00,2.91,18.04,4.54,0.53,6.15,334.89,6.40
11,1990-02-16 00:00:00,5.10,7.91,2.88,17.99,4.47,0.53,6.11,332.72,6.33
12,1990-02-20 00:00:00,5.04,7.85,2.83,17.88,4.39,0.55,6.01,327.99,6.25
13,1990-02-21 00:00:00,5.01,7.97,2.81,18.23,4.33,0.52,5.91,327.67,6.28
14,1990-02-22 00:00:00,5.06,7.73,2.82,17.95,4.28,0.53,5.87,325.70,6.22
15,1990-02-23 00:00:00,5.07,7.79,2.81,17.84,4.20,0.53,5.88,324.15,6.22
16,1990-02-26 00:00:00,5.13,7.97,2.84,18.08,4.30,0.54,5.93,328.67,6.37
17,1990-02-27 00:00:00,5.16,7.85,2.88,18.04,4.30,0.53,6.00,330.26,6.38
18,1990-02-28 00:00:00,5.22,7.97,2.89,18.06,4.32,0.54,6.06,331.89,6.20
19,1990-03-01 00:00:00,5.26,8.03,2.88,18.08,4.35,0.55,5.98,332.74,6.13
20,1990-03-02 00:00:00,5.41,7.91,2.92,18.23,4.43,0.57,5.89,335.54,6.17
21,1990-03-05 00:00:00,5.39,8.08,2.89,18.25,4.36,0.57,5.89,333.74,6.10
22,1990-03-06 00:00:00,5.40,8.26,2.92,18.39,4.45,0.57,5.97,337.93,6.22
23,1990-03-07 00:00:00,5.36,8.29,2.93,18.34,4.45,0.56,6.06,336.95,6.13
24,1990-03-08 00:00:00,5.34,8.61,2.95,18.60,4.50,0.58,6.18,340.27,6.17
25,1990-03-09 00:00:00,5.33,8.64,2.93,18.52,4.48,0.58,6.10,337.93,6.12
26,1990-03-12 00:00:00,5.34,8.58,2.92,18.73,4.46,0.59,6.22,338.67,6.13
27,1990-03-13 00:00:00,5.29,8.64,2.90,18.47,4.38,0.58,6.18,336.00,6.02
28,1990-03-14 00:00:00,5.28,8.67,2.95,18.47,4.44,0.59,6.15,336.87,6.13
29,1990-03-15 00:00:00,5.36,8.61,2.96,18.60,4.58,0.61,6.18,338.07,6.18
...,...,...,...,...,...,...,...,...,...,...
5442,2011-09-02 00:00:00,12.04,374.05,15.61,166.98,64.07,25.80,63.30,1173.97,72.14
5443,2011-09-06 00:00:00,11.77,379.74,15.11,165.11,64.64,25.51,62.45,1165.24,71.15
5444,2011-09-07 00:00:00,12.25,383.93,15.65,167.31,65.43,26.00,61.62,1198.62,73.65
5445,2011-09-08 00:00:00,12.03,384.14,15.44,165.25,64.95,26.22,61.34,1185.90,72.82
5446,2011-09-09 00:00:00,11.58,377.48,14.95,161.37,63.64,25.74,59.99,1154.23,71.01
5447,2011-09-12 00:00:00,11.55,379.94,14.87,162.42,63.59,25.89,60.14,1162.27,71.84
5448,2011-09-13 00:00:00,11.63,384.62,15.26,163.43,63.61,26.04,60.54,1172.87,71.65
5449,2011-09-14 00:00:00,11.73,389.30,15.64,167.24,63.73,26.50,61.58,1188.68,72.64
5450,2011-09-15 00:00:00,11.98,392.96,16.08,170.09,64.40,26.99,63.22,1209.11,74.01
5451,2011-09-16 00:00:00,11.97,400.50,16.33,172.99,64.59,27.12,62.05,1216.01,74.55
5452,2011-09-19 00:00:00,11.58,411.63,16.18,173.13,64.14,27.21,60.56,1204.09,73.70
5453,2011-09-20 00:00:00,11.25,413.45,16.04,174.72,64.22,26.98,60.39,1202.09,74.01
5454,2011-09-21 00:00:00,10.84,412.14,15.38,173.02,63.13,25.99,60.79,1166.76,71.97
5455,2011-09-22 00:00:00,10.11,401.82,15.04,168.62,61.92,25.06,60.92,1129.56,69.24
5456,2011-09-23 00:00:00,10.07,404.30,15.21,169.34,61.59,25.06,60.34,1136.43,69.31
5457,2011-09-26 00:00:00,10.45,403.17,15.57,174.51,62.69,25.44,61.89,1162.95,71.72
5458,2011-09-27 00:00:00,10.48,399.26,15.76,177.71,63.82,25.67,62.43,1175.38,72.91
5459,2011-09-28 00:00:00,9.97,397.01,15.45,177.55,63.25,25.58,61.97,1151.06,72.07
5460,2011-09-29 00:00:00,10.06,390.57,15.86,179.17,63.90,25.45,62.58,1160.40,73.88
5461,2011-09-30 00:00:00,9.57,381.32,15.22,174.87,63.69,24.89,61.90,1131.42,72.63
5462,2011-10-03 00:00:00,8.90,374.60,14.69,173.29,62.08,24.53,60.29,1099.23,71.15
5463,2011-10-04 00:00:00,9.12,372.50,14.86,174.74,62.17,25.34,60.45,1123.95,72.83
5464,2011-10-05 00:00:00,9.37,378.25,15.27,176.85,62.35,25.89,60.29,1144.03,73.95
5465,2011-10-06 00:00:00,9.88,377.37,15.53,181.69,62.81,26.34,60.57,1164.97,73.89
5466,2011-10-07 00:00:00,9.71,369.80,15.50,182.39,63.13,26.25,61.02,1155.46,73.56
5467,2011-10-10 00:00:00,10.09,388.81,16.14,186.62,64.43,26.94,61.87,1194.89,76.28
5468,2011-10-11 00:00:00,10.30,400.29,16.14,185.00,63.96,27.00,60.95,1195.54,76.27
5469,2011-10-12 00:00:00,10.05,402.19,16.40,186.12,64.33,26.96,62.70,1207.25,77.16
5470,2011-10-13 00:00:00,10.10,408.43,16.22,186.82,64.23,27.18,62.36,1203.66,76.37
5471,2011-10-14 00:00:00,10.26,422.00,16.60,190.53,64.72,27.27,62.24,1224.58,78.11

In [ ]:
prices = df