# Movie lens

> The MovieLens 1M data set contains 1 million ratings collected from 6000 users on4000 movies. Itâ€™s spread across 3 tables: ratings, user information, and movie infor-mation.

We have 3 dataset: user, rating of user, and movie info

In [2]:
import pandas as pd
unames = ['user_id', 'gender', 'age', 'occupation', 'zip']
users = pd.read_table('data/ml-1m/users.dat', sep='::', header=None, names=unames)
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('data/ml-1m/movies.dat', sep='::', header=None, names=mnames)
rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('data/ml-1m/ratings.dat', sep='::', header=None, names=rnames)

/home/khanhlq/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()
/home/khanhlq/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
/home/khanhlq/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:7: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.

In [4]:
users

      user_id gender  age  occupation    zip
0           1      F    1          10  48067
1           2      M   56          16  70072
2           3      M   25          15  55117
3           4      M   45           7  02460
4           5      M   25          20  55455
5           6      F   50           9  55117
6           7      M   35           1  06810
7           8      M   25          12  11413
8           9      M   25          17  61614
9          10      F   35           1  95370
10         11      F   25           1  04093
11         12      M   25          12  32793
12         13      M   45           1  93304
13         14      M   35           0  60126
14         15      M   25           7  22903
15         16      F   35           0  20670
16         17      M   50           1  95350
17         18      F   18           3  95825
18         19      M    1          10  48073
19         20      M   25          14  55113
20         21      M   18          16  99353
21         22      M   18          15  53706
22         23      M   35           0  90049
23         24      F   25           7  10023
24         25      M   18           4  01609
25         26      M   25           7  23112
26         27      M   25          11  19130
27         28      F   25           1  14607
28         29      M   35           7  33407
29         30      F   35           7  19143
...       ...    ...  ...         ...    ...
6010     6011      M   35          15  80538
6011     6012      M   35          15  02871
6012     6013      F   25          20  32301
6013     6014      M   45           1  80634
6014     6015      F   25           9  80013
6015     6016      M   45           1  37209
6016     6017      F   35           7  21117
6017     6018      M   35           1  48906
6018     6019      M   25           0  10024
6019     6020      M   50          16  10023
6020     6021      M   25          12  08876
6021     6022      M   25          17  57006
6022     6023      M   25           0  43213
6023     6024      M   25          12  53705
6024     6025      F   25           1  32607
6025     6026      M   35           6  11210
6026     6027      M   18           4  20742
6027     6028      M   18           4  94133
6028     6029      F   25           1  23185
6029     6030      M   25          17  32618
6030     6031      F   18           0  45123
6031     6032      M   45           7  55108
6032     6033      M   50          13  78232
6033     6034      M   25          14  94117
6034     6035      F   25           1  78734
6035     6036      F   25          15  32603
6036     6037      F   45           1  76006
6037     6038      F   56           1  14706
6038     6039      F   45           0  01060
6039     6040      M   25           6  11106

[6040 rows x 5 columns]

In [5]:
movies

,movie_id,title,genres
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

In [6]:
ratings

         user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
5              1      1197       3  978302268
6              1      1287       5  978302039
7              1      2804       5  978300719
8              1       594       4  978302268
9              1       919       4  978301368
10             1       595       5  978824268
11             1       938       4  978301752
12             1      2398       4  978302281
13             1      2918       4  978302124
14             1      1035       5  978301753
15             1      2791       4  978302188
16             1      2687       3  978824268
17             1      2018       4  978301777
18             1      3105       5  978301713
19             1      2797       4  978302039
20             1      2321       3  978302205
21             1       720       3  978300760
22             1      1270       5  978300055
23             1       527       5  978824195
24             1      2340       3  978300103
25             1        48       5  978824351
26             1      1097       4  978301953
27             1      1721       4  978300055
28             1      1545       4  978824139
29             1       745       3  978824268
...          ...       ...     ...        ...
1000179     6040      2762       4  956704584
1000180     6040      1036       3  956715455
1000181     6040       508       4  956704972
1000182     6040      1041       4  957717678
1000183     6040      3735       4  960971654
1000184     6040      2791       4  956715569
1000185     6040      2794       1  956716438
1000186     6040       527       5  956704219
1000187     6040      2003       1  956716294
1000188     6040       535       4  964828734
1000189     6040      2010       5  957716795
1000190     6040      2011       4  956716113
1000191     6040      3751       4  964828782
1000192     6040      2019       5  956703977
1000193     6040       541       4  956715288
1000194     6040      1077       5  964828799
1000195     6040      1079       2  956715648
1000196     6040       549       4  956704746
1000197     6040      2020       3  956715288
1000198     6040      2021       3  956716374
1000199     6040      2022       5  956716207
1000200     6040      2028       5  956704519
1000201     6040      1080       4  957717322
1000202     6040      1089       4  956704996
1000203     6040      1090       3  956715518
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

## Question 1:

In [3]:
data = pd.merge(pd.merge(ratings, users), movies)

In [4]:
mean_ratings = pd.pivot_table(data, values='rating', index='title', columns='gender', aggfunc='mean')
mean_ratings

gender                                                 F         M
title
$1,000,000 Duck (1971)                          3.375000  2.761905
'Night Mother (1986)                            3.388889  3.352941
'Til There Was You (1997)                       2.675676  2.733333
'burbs, The (1989)                              2.793478  2.962085
...And Justice for All (1979)                   3.828571  3.689024
1-900 (1994)                                    2.000000  3.000000
10 Things I Hate About You (1999)               3.646552  3.311966
101 Dalmatians (1961)                           3.791444  3.500000
101 Dalmatians (1996)                           3.240000  2.911215
12 Angry Men (1957)                             4.184397  4.328421
13th Warrior, The (1999)                        3.112000  3.168000
187 (1997)                                      2.428571  2.791667
2 Days in the Valley (1996)                     3.488889  3.244813
20 Dates (1998)                                 2.620690  2.918182
20,000 Leagues Under the Sea (1954)             3.670103  3.709205
200 Cigarettes (1999)                           3.169014  2.700000
2001: A Space Odyssey (1968)                    3.825581  4.129738
2010 (1984)                                     3.446809  3.413712
24 7: Twenty Four Seven (1997)                  5.000000  3.750000
24-hour Woman (1998)                            2.000000  1.600000
28 Days (2000)                                  3.209424  2.977707
3 Ninjas: High Noon On Mega Mountain (1998)     1.400000  1.351351
3 Strikes (2000)                                     NaN  2.750000
301, 302 (1995)                                 3.000000  2.857143
39 Steps, The (1935)                            3.965517  4.107692
400 Blows, The (Les Quatre cents coups) (1959)  4.489362  4.264286
42 Up (1998)                                    3.966667  4.362069
52 Pick-Up (1986)                               3.304348  3.299145
54 (1998)                                       2.701754  2.782178
7th Voyage of Sinbad, The (1958)                3.409091  3.658879
...                                                  ...       ...
Wrongfully Accused (1998)                       2.666667  2.540541
Wyatt Earp (1994)                               3.147059  3.283898
X-Files: Fight the Future, The (1998)           3.489474  3.493797
X-Men (2000)                                    3.682310  3.851702
X: The Unknown (1956)                           2.250000  3.125000
Xiu Xiu: The Sent-Down Girl (Tian yu) (1998)    3.821429  3.536585
Yankee Zulu (1994)                              3.000000  3.000000
Yards, The (1999)                               2.687500  3.360656
Year My Voice Broke, The (1987)                 4.000000  3.705882
Year of Living Dangerously (1982)               3.951220  3.869403
Year of the Horse (1997)                             NaN  3.250000
Yellow Submarine (1968)                         3.714286  3.689286
Yojimbo (1961)                                  4.423077  4.402116
You Can't Take It With You (1938)               4.192308  3.921569
You So Crazy (1994)                             3.666667  2.300000
You've Got Mail (1998)                          3.542424  3.275591
Young Doctors in Love (1982)                    1.923077  2.742424
Young Frankenstein (1974)                       4.289963  4.239177
Young Guns (1988)                               3.371795  3.425620
Young Guns II (1990)                            2.934783  2.904025
Young Poisoner's Handbook, The (1995)           4.000000  3.532258
Young Sherlock Holmes (1985)                    3.514706  3.363344
Young and Innocent (1937)                       2.500000  3.500000
Your Friends and Neighbors (1998)               2.888889  3.536585
Zachariah (1971)                                     NaN  3.500000
Zed & Two Noughts, A (1985)                     3.500000  3.380952
Zero Effect (1998)                              3.864407  3.723140
Zero Kelvin (Kjï¿½rlighetens kjï¿½tere) (1995)           NaN  3.500000
Zeus and Roxanne (1997)                         2.777778  2.357143
eXistenZ (1999)                                 3.098592  3.289086

[3706 rows x 2 columns]

In [5]:
ratings_by_title = data.groupby('title').size()
ratings_by_title

title
$1,000,000 Duck (1971)                              37
'Night Mother (1986)                                70
'Til There Was You (1997)                           52
'burbs, The (1989)                                 303
...And Justice for All (1979)                      199
1-900 (1994)                                         2
10 Things I Hate About You (1999)                  700
101 Dalmatians (1961)                              565
101 Dalmatians (1996)                              364
12 Angry Men (1957)                                616
13th Warrior, The (1999)                           750
187 (1997)                                          55
2 Days in the Valley (1996)                        286
20 Dates (1998)                                    139
20,000 Leagues Under the Sea (1954)                575
200 Cigarettes (1999)                              181
2001: A Space Odyssey (1968)                      1716
2010 (1984)                                        470
24 7: Twenty Four Seven (1997)                       5
24-hour Woman (1998)                                 9
28 Days (2000)                                     505
3 Ninjas: High Noon On Mega Mountain (1998)         47
3 Strikes (2000)                                     4
301, 302 (1995)                                      9
39 Steps, The (1935)                               253
400 Blows, The (Les Quatre cents coups) (1959)     187
42 Up (1998)                                        88
52 Pick-Up (1986)                                  140
54 (1998)                                          259
7th Voyage of Sinbad, The (1958)                   258
                                                  ...
Wrongfully Accused (1998)                          123
Wyatt Earp (1994)                                  270
X-Files: Fight the Future, The (1998)              996
X-Men (2000)                                      1511
X: The Unknown (1956)                               12
Xiu Xiu: The Sent-Down Girl (Tian yu) (1998)        69
Yankee Zulu (1994)                                   2
Yards, The (1999)                                   77
Year My Voice Broke, The (1987)                     27
Year of Living Dangerously (1982)                  391
Year of the Horse (1997)                             4
Yellow Submarine (1968)                            399
Yojimbo (1961)                                     215
You Can't Take It With You (1938)                   77
You So Crazy (1994)                                 13
You've Got Mail (1998)                             838
Young Doctors in Love (1982)                        79
Young Frankenstein (1974)                         1193
Young Guns (1988)                                  562
Young Guns II (1990)                               369
Young Poisoner's Handbook, The (1995)               79
Young Sherlock Holmes (1985)                       379
Young and Innocent (1937)                           10
Your Friends and Neighbors (1998)                  109
Zachariah (1971)                                     2
Zed & Two Noughts, A (1985)                         29
Zero Effect (1998)                                 301
Zero Kelvin (Kjï¿½rlighetens kjï¿½tere) (1995)           2
Zeus and Roxanne (1997)                             23
eXistenZ (1999)                                    410
dtype: int64

In [6]:
active_titles = ratings_by_title.index[ratings_by_title > 250]
active_titles

Index([u''burbs, The (1989)', u'10 Things I Hate About You (1999)',
       u'101 Dalmatians (1961)', u'101 Dalmatians (1996)',
       u'12 Angry Men (1957)', u'13th Warrior, The (1999)',
       u'2 Days in the Valley (1996)', u'20,000 Leagues Under the Sea (1954)',
       u'2001: A Space Odyssey (1968)', u'2010 (1984)',
       ...
       u'X-Men (2000)', u'Year of Living Dangerously (1982)',
       u'Yellow Submarine (1968)', u'You've Got Mail (1998)',
       u'Young Frankenstein (1974)', u'Young Guns (1988)',
       u'Young Guns II (1990)', u'Young Sherlock Holmes (1985)',
       u'Zero Effect (1998)', u'eXistenZ (1999)'],
      dtype='object', name=u'title', length=1214)

In [7]:
mean_ratings = mean_ratings.ix[active_titles]
mean_ratings

gender                                                     F         M
title
'burbs, The (1989)                                  2.793478  2.962085
10 Things I Hate About You (1999)                   3.646552  3.311966
101 Dalmatians (1961)                               3.791444  3.500000
101 Dalmatians (1996)                               3.240000  2.911215
12 Angry Men (1957)                                 4.184397  4.328421
13th Warrior, The (1999)                            3.112000  3.168000
2 Days in the Valley (1996)                         3.488889  3.244813
20,000 Leagues Under the Sea (1954)                 3.670103  3.709205
2001: A Space Odyssey (1968)                        3.825581  4.129738
2010 (1984)                                         3.446809  3.413712
28 Days (2000)                                      3.209424  2.977707
39 Steps, The (1935)                                3.965517  4.107692
54 (1998)                                           2.701754  2.782178
7th Voyage of Sinbad, The (1958)                    3.409091  3.658879
8MM (1999)                                          2.906250  2.850962
About Last Night... (1986)                          3.188679  3.140909
Absent Minded Professor, The (1961)                 3.469388  3.446809
Absolute Power (1997)                               3.469136  3.327759
Abyss, The (1989)                                   3.659236  3.689507
Ace Ventura: Pet Detective (1994)                   3.000000  3.197917
Ace Ventura: When Nature Calls (1995)               2.269663  2.543333
Addams Family Values (1993)                         3.000000  2.878531
Addams Family, The (1991)                           3.186170  3.163498
Adventures in Babysitting (1987)                    3.455782  3.208122
Adventures of Buckaroo Bonzai Across the 8th Di...  3.308511  3.402321
Adventures of Priscilla, Queen of the Desert, T...  3.989071  3.688811
Adventures of Robin Hood, The (1938)                4.166667  3.918367
African Queen, The (1951)                           4.324232  4.223822
Age of Innocence, The (1993)                        3.827068  3.339506
Agnes of God (1985)                                 3.534884  3.244898
...                                                      ...       ...
White Men Can't Jump (1992)                         3.028777  3.231061
Who Framed Roger Rabbit? (1988)                     3.569378  3.713251
Who's Afraid of Virginia Woolf? (1966)              4.029703  4.096939
Whole Nine Yards, The (2000)                        3.296552  3.404814
Wild Bunch, The (1969)                              3.636364  4.128099
Wild Things (1998)                                  3.392000  3.459082
Wild Wild West (1999)                               2.275449  2.131973
William Shakespeare's Romeo and Juliet (1996)       3.532609  3.318644
Willow (1988)                                       3.658683  3.453543
Willy Wonka and the Chocolate Factory (1971)        4.063953  3.789474
Witness (1985)                                      4.115854  3.941504
Wizard of Oz, The (1939)                            4.355030  4.203138
Wolf (1994)                                         3.074074  2.899083
Women on the Verge of a Nervous Breakdown (1988)    3.934307  3.865741
Wonder Boys (2000)                                  4.043796  3.913649
Working Girl (1988)                                 3.606742  3.312500
World Is Not Enough, The (1999)                     3.337500  3.388889
Wrong Trousers, The (1993)                          4.588235  4.478261
Wyatt Earp (1994)                                   3.147059  3.283898
X-Files: Fight the Future, The (1998)               3.489474  3.493797
X-Men (2000)                                        3.682310  3.851702
Year of Living Dangerously (1982)                   3.951220  3.869403
Yellow Submarine (1968)                             3.714286  3.689286
You've Got Mail (1998)                              3.542424  3.275591
Young Frankenstein (1974)                           4.289963  4.239177
Young Guns (1988)                                   3.371795  3.425620
Young Guns II (1990)                                2.934783  2.904025
Young Sherlock Holmes (1985)                        3.514706  3.363344
Zero Effect (1998)                                  3.864407  3.723140
eXistenZ (1999)                                     3.098592  3.289086

[1214 rows x 2 columns]

In [8]:
mean_ratings['diff'] = mean_ratings['M'] - mean_ratings['F']
sort_by_diff = mean_ratings.sort_index(by='diff')
sort_by_diff[::1][:15]

/home/khanhlq/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  from ipykernel import kernelapp as app

gender                                        F         M      diff
title
Dirty Dancing (1987)                   3.790378  2.959596 -0.830782
Jumpin' Jack Flash (1986)              3.254717  2.578358 -0.676359
Grease (1978)                          3.975265  3.367041 -0.608224
Little Women (1994)                    3.870588  3.321739 -0.548849
Steel Magnolias (1989)                 3.901734  3.365957 -0.535777
Anastasia (1997)                       3.800000  3.281609 -0.518391
Rocky Horror Picture Show, The (1975)  3.673016  3.160131 -0.512885
Color Purple, The (1985)               4.158192  3.659341 -0.498851
Age of Innocence, The (1993)           3.827068  3.339506 -0.487561
Free Willy (1993)                      2.921348  2.438776 -0.482573
French Kiss (1995)                     3.535714  3.056962 -0.478752
Little Shop of Horrors, The (1960)     3.650000  3.179688 -0.470312
Guys and Dolls (1955)                  4.051724  3.583333 -0.468391
Mary Poppins (1964)                    4.197740  3.730594 -0.467147
Patch Adams (1998)                     3.473282  3.008746 -0.464536

In [9]:
rating_std_by_title = data.groupby('title')['rating'].std()
rating_std_by_title

title
$1,000,000 Duck (1971)                            1.092563
'Night Mother (1986)                              1.118636
'Til There Was You (1997)                         1.020159
'burbs, The (1989)                                1.107760
...And Justice for All (1979)                     0.878110
1-900 (1994)                                      0.707107
10 Things I Hate About You (1999)                 0.989815
101 Dalmatians (1961)                             0.982103
101 Dalmatians (1996)                             1.098717
12 Angry Men (1957)                               0.812731
13th Warrior, The (1999)                          1.140421
187 (1997)                                        1.057919
2 Days in the Valley (1996)                       0.921592
20 Dates (1998)                                   1.151943
20,000 Leagues Under the Sea (1954)               0.869685
200 Cigarettes (1999)                             1.111964
2001: A Space Odyssey (1968)                      1.042504
2010 (1984)                                       0.946618
24 7: Twenty Four Seven (1997)                    1.000000
24-hour Woman (1998)                              0.666667
28 Days (2000)                                    0.920278
3 Ninjas: High Noon On Mega Mountain (1998)       0.791958
3 Strikes (2000)                                  1.258306
301, 302 (1995)                                   0.781736
39 Steps, The (1935)                              0.853501
400 Blows, The (Les Quatre cents coups) (1959)    0.869893
42 Up (1998)                                      0.906265
52 Pick-Up (1986)                                 0.911162
54 (1998)                                         1.035481
7th Voyage of Sinbad, The (1958)                  0.931531
                                                    ...
Wrongfully Accused (1998)                         1.249283
Wyatt Earp (1994)                                 0.922257
X-Files: Fight the Future, The (1998)             0.897204
X-Men (2000)                                      0.915067
X: The Unknown (1956)                             1.267304
Xiu Xiu: The Sent-Down Girl (Tian yu) (1998)      1.026503
Yankee Zulu (1994)                                0.000000
Yards, The (1999)                                 1.071440
Year My Voice Broke, The (1987)                   0.786278
Year of Living Dangerously (1982)                 0.880997
Year of the Horse (1997)                          1.258306
Yellow Submarine (1968)                           1.075429
Yojimbo (1961)                                    0.853238
You Can't Take It With You (1938)                 0.938833
You So Crazy (1994)                               1.445595
You've Got Mail (1998)                            1.037854
Young Doctors in Love (1982)                      0.992507
Young Frankenstein (1974)                         0.872810
Young Guns (1988)                                 1.017437
Young Guns II (1990)                              1.071959
Young Poisoner's Handbook, The (1995)             0.787355
Young Sherlock Holmes (1985)                      0.891176
Young and Innocent (1937)                         1.251666
Your Friends and Neighbors (1998)                 1.128659
Zachariah (1971)                                  2.121320
Zed & Two Noughts, A (1985)                       1.052794
Zero Effect (1998)                                1.042932
Zero Kelvin (Kjï¿½rlighetens kjï¿½tere) (1995)        0.707107
Zeus and Roxanne (1997)                           1.122884
eXistenZ (1999)                                   1.178568
Name: rating, dtype: float64